<?php
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'AFG'", "ME", "Middle East", "AF" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'ALA'", "EU", "Europe", "AX" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'ALB'", "EU", "Europe", "AL" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'DZA'", "AF", "Africa", "DZ" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'ASM'", "OC", "Oceania", "AS" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'AND'", "EU", "Europe", "AD" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'AGO'", "AF", "Africa", "AO" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'AIA'", "SA", "South America", "AI" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'ATG'", "SA", "South America", "AG" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'ARG'", "SA", "South America", "AR" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'ARM'", "EU", "Europe", "AM" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'ABW'", "SA", "South America", "AW" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'AUS'", "OC", "Oceania", "AU" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'AUT'", "EU", "Europe", "AT" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'AZE'", "ME", "Middle East", "AZ" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'BHS'", "SA", "South America", "BS" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'BHR'", "ME", "Middle East", "BH" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'BGD'", "SS", "South Asia", "BD" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'BRB'", "SA", "South America", "BB" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'BLR'", "EU", "Europe", "BY" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'BEL'", "EU", "Europe", "BE" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'BLZ'", "SA", "South America", "BZ" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'BEN'", "AF", "Africa", "BJ" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'BMU'", "NA", "North America", "BM" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'BTN'", "SS", "South Asia", "BT" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'BOL'", "SA", "South America", "BO" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'BES'", "SA", "South America", "" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'BIH'", "EU", "Europe", "BA" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'BWA'", "AF", "Africa", "BW" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'BRA'", "SA", "South America", "BR" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'VGB'", "SA", "South America", "VG" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'BRN'", "OC", "Oceania", "BN" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'BGR'", "EU", "Europe", "BG" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'BFA'", "AF", "Africa", "BF" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'BDI'", "AF", "Africa", "BI" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'CPV'", "AF", "Africa", "CV" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'KHM'", "SS", "South Asia", "KH" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'CMR'", "AF", "Africa", "CM" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'CAN'", "NA", "North America", "CA" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'CYM'", "SA", "South America", "KY" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'CAF'", "AF", "Africa", "CF" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'TCD'", "AF", "Africa", "TD" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'CHL'", "SA", "South America", "CL" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'CHN'", "SS", "South Asia", "CN" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'HKG'", "SS", "South Asia", "HK" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'MAC'", "SS", "South Asia", "MO" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'COL'", "SA", "South America", "CO" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'COM'", "AF", "Africa", "KM" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'COG'", "AF", "Africa", "CG" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'COK'", "OC", "Oceania", "CK" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'CRI'", "SA", "South America", "CR" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'CIV'", "AF", "Africa", "CI" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'HRV'", "EU", "Europe", "HR" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'CUB'", "SA", "South America", "CU" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'CUW'", "SA", "South America", "CW" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'CYP'", "EU", "Europe", "CY" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'CZE'", "EU", "Europe", "CZ" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'PRK'", "SS", "South Asia", "KP" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'COD'", "AF", "Africa", "CD" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'DNK'", "EU", "Europe", "DK" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'DJI'", "AF", "Africa", "DJ" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'DMA'", "SA", "South America", "DM" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'DOM'", "SA", "South America", "DO" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'ECU'", "SA", "South America", "EC" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'EGY'", "AF", "Africa", "EG" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'SLV'", "SA", "South America", "SV" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'GNQ'", "AF", "Africa", "GQ" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'ERI'", "AF", "Africa", "ER" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'EST'", "EU", "Europe", "EE" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'ETH'", "AF", "Africa", "ET" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'FRO'", "EU", "Europe", "FO" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'FLK'", "SA", "South America", "FK" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'FJI'", "OC", "Oceania", "FJ" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'FIN'", "EU", "Europe", "FI" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'FRA'", "EU", "Europe", "FR" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'GUF'", "SA", "South America", "GF" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'PYF'", "OC", "Oceania", "PF" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'GAB'", "AF", "Africa", "GA" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'GMB'", "AF", "Africa", "GM" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'GEO'", "EU", "Europe", "GE" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'DEU'", "EU", "Europe", "DE" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'GHA'", "AF", "Africa", "GH" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'GIB'", "EU", "Europe", "GI" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'GRC'", "EU", "Europe", "GR" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'GRL'", "NA", "North America", "GL" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'GRD'", "SA", "South America", "GD" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'GLP'", "SA", "South America", "GP" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'GUM'", "OC", "Oceania", "GU" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'GTM'", "SA", "South America", "GT" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'GGY'", "EU", "Europe", "GG" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'GIN'", "AF", "Africa", "GN" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'GNB'", "AF", "Africa", "GW" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'GUY'", "SA", "South America", "GY" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'HTI'", "SA", "South America", "HT" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'VAT'", "EU", "Europe", "VA" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'HND'", "SA", "South America", "HN" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'HUN'", "EU", "Europe", "HU" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'ISL'", "EU", "Europe", "IS" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'IND'", "SS", "South Asia", "IN" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'IDN'", "OC", "Oceania", "ID" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'IRN'", "ME", "Middle East", "IR" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'IRQ'", "ME", "Middle East", "IQ" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'IRL'", "EU", "Europe", "IE" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'IMN'", "EU", "Europe", "IM" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'ISR'", "ME", "Middle East", "IL" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'ITA'", "EU", "Europe", "IT" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'JAM'", "SA", "South America", "JM" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'JPN'", "SS", "South Asia", "JP" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'JEY'", "EU", "Europe", "JE" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'JOR'", "ME", "Middle East", "JO" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'KAZ'", "NS", "North Asia", "KZ" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'KEN'", "AF", "Africa", "KE" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'KIR'", "OC", "Oceania", "KI" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'KWT'", "ME", "Middle East", "KW" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'KGZ'", "ME", "Middle East", "KG" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'LAO'", "SS", "South Asia", "LA" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'LVA'", "EU", "Europe", "LV" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'LBN'", "ME", "Middle East", "LB" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'LSO'", "AF", "Africa", "LS" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'LBR'", "AF", "Africa", "LR" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'LBY'", "AF", "Africa", "LY" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'LIE'", "EU", "Europe", "LI" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'LTU'", "EU", "Europe", "LT" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'LUX'", "EU", "Europe", "LU" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'MDG'", "AF", "Africa", "MG" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'MWI'", "AF", "Africa", "MW" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'MYS'", "OC", "Oceania", "MY" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'MDV'", "SS", "South Asia", "MV" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'MLI'", "AF", "Africa", "ML" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'MLT'", "EU", "Europe", "MT" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'MHL'", "OC", "Oceania", "MH" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'MTQ'", "SA", "South America", "MQ" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'MRT'", "AF", "Africa", "MR" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'MUS'", "AF", "Africa", "MU" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'MYT'", "AF", "Africa", "YT" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'MEX'", "NA", "North America", "MX" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'FSM'", "OC", "Oceania", "FM" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'MCO'", "EU", "Europe", "MC" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'MNG'", "NS", "North Asia", "MN" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'MNE'", "EU", "Europe", "ME" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'MSR'", "SA", "South America", "MS" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'MAR'", "AF", "Africa", "MA" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'MOZ'", "AF", "Africa", "MZ" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'MMR'", "SS", "South Asia", "MM" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'NAM'", "AF", "Africa", "NA" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'NRU'", "OC", "Oceania", "NR" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'NPL'", "SS", "South Asia", "NP" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'NLD'", "EU", "Europe", "NL" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'NCL'", "OC", "Oceania", "NC" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'NZL'", "OC", "Oceania", "NZ" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'NIC'", "SA", "South America", "NI" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'NER'", "AF", "Africa", "NE" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'NGA'", "AF", "Africa", "NG" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'NIU'", "OC", "Oceania", "NU" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'NFK'", "OC", "Oceania", "NF" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'MNP'", "OC", "Oceania", "MP" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'NOR'", "EU", "Europe", "NO" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'OMN'", "ME", "Middle East", "OM" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'PAK'", "ME", "Middle East", "PK" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'PLW'", "OC", "Oceania", "PW" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'PSE'", "ME", "Middle East", "PS" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'PAN'", "SA", "South America", "PA" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'PNG'", "OC", "Oceania", "PG" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'PRY'", "SA", "South America", "PY" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'PER'", "SA", "South America", "PE" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'PHL'", "SS", "South Asia", "PH" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'PCN'", "OC", "Oceania", "PN" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'POL'", "EU", "Europe", "PL" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'PRT'", "EU", "Europe", "PT" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'PRI'", "SA", "South America", "PR" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'QAT'", "ME", "Middle East", "QA" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'KOR'", "SS", "South Asia", "KR" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'MDA'", "EU", "Europe", "MD" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'REU'", "AF", "Africa", "RE" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'ROU'", "EU", "Europe", "RO" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'RUS'", "NS", "North Asia", "RU" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'RWA'", "AF", "Africa", "RW" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'BLM'", "SA", "South America", "BL" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'SHN'", "AF", "Africa", "SH" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'KNA'", "SA", "South America", "KN" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'LCA'", "SA", "South America", "LC" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'MAF'", "SA", "South America", "MF" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'SPM'", "NA", "North America", "PM" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'VCT'", "SA", "South America", "VC" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'WSM'", "OC", "Oceania", "WS" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'SMR'", "EU", "Europe", "SM" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'STP'", "AF", "Africa", "ST" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'SAU'", "ME", "Middle East", "SA" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'SEN'", "AF", "Africa", "SN" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'SRB'", "EU", "Europe", "RS" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'SYC'", "AF", "Africa", "SC" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'SLE'", "AF", "Africa", "SL" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'SGP'", "SS", "South Asia", "SG" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'SXM'", "SA", "South America", "SX" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'SVK'", "EU", "Europe", "SK" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'SVN'", "EU", "Europe", "SI" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'SLB'", "OC", "Oceania", "SB" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'SOM'", "AF", "Africa", "SO" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'ZAF'", "AF", "Africa", "ZA" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'SSD'", "AF", "Africa", "SS" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'ESP'", "EU", "Europe", "ES" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'LKA'", "SS", "South Asia", "LK" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'SDN'", "AF", "Africa", "SD" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'SUR'", "SA", "South America", "SR" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'SJM'", "EU", "Europe", "SJ" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'SWZ'", "AF", "Africa", "SZ" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'SWE'", "EU", "Europe", "SE" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'CHE'", "EU", "Europe", "CH" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'SYR'", "ME", "Middle East", "SY" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'TWN'", "SS", "South Asia", "TW" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'TJK'", "ME", "Middle East", "TJ" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'THA'", "SS", "South Asia", "TH" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'MKD'", "EU", "Europe", "MK" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'TLS'", "OC", "Oceania", "TL" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'TGO'", "AF", "Africa", "TG" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'TKL'", "OC", "Oceania", "TK" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'TON'", "OC", "Oceania", "TO" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'TTO'", "SA", "South America", "TT" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'TUN'", "AF", "Africa", "TN" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'TUR'", "EU", "Europe", "TR" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'TKM'", "ME", "Middle East", "TM" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'TCA'", "SA", "South America", "TC" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'TUV'", "OC", "Oceania", "TV" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'UGA'", "AF", "Africa", "UG" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'UKR'", "EU", "Europe", "UA" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'ARE'", "ME", "Middle East", "AE" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'GBR'", "EU", "Europe", "GB" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'TZA'", "AF", "Africa", "TZ" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'USA'", "NA", "North America", "US" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'VIR'", "SA", "South America", "VI" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'URY'", "SA", "South America", "UY" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'UZB'", "ME", "Middle East", "ZU" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'VUT'", "OC", "Oceania", "VU" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'VEN'", "SA", "South America", "VE" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'VNM'", "SS", "South Asia", "VN" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'WLF'", "OC", "Oceania", "WF" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'ESH'", "AF", "Africa", "EH" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'YEM'", "ME", "Middle East", "YE" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'ZMB'", "AF", "Africa", "ZM" ));
$wpdb->query( $wpdb->prepare("UPDATE {$wpdb->projectmanager_countries} SET `region_code` = '%s', `region_name` = '%s', `code2` = '%s' WHERE `code` = 'ZWE'", "AF", "Africa", "ZW" ));
?>