INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("AFG", "Afghanistan", "ME", "Middle East", "AF");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("ALA", "Åland Islands", "EU", "Europe", "AX");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("ALB", "Albania", "EU", "Europe", "AL");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("DZA", "Algeria", "AF", "Africa", "DZ");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("ASM", "American Samoa", "OC", "Oceania", "AS");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("AND", "Andorra", "EU", "Europe", "AD");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("AGO", "Angola", "AF", "Africa", "AO");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("AIA", "Anguilla", "SA", "South America", "AI");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("ATG", "Antigua and Barbuda", "SA", "South America", "AG");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("ARG", "Argentina", "SA", "South America", "AR");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("ARM", "Armenia", "EU", "Europe", "AM");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("ABW", "Aruba", "SA", "South America", "AW");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("AUS", "Australia", "OC", "Oceania", "AU");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("AUT", "Austria", "EU", "Europe", "AT");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("AZE", "Azerbaijan", "ME", "Middle East", "AZ");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("BHS", "Bahamas", "SA", "South America", "BS");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("BHR", "Bahrain", "ME", "Middle East", "BH");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("BGD", "Bangladesh", "SS", "South Asia", "BD");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("BRB", "Barbados", "SA", "South America", "BB");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("BLR", "Belarus", "EU", "Europe", "BY");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("BEL", "Belgium", "EU", "Europe", "BE");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("BLZ", "Belize", "SA", "South America", "BZ");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("BEN", "Benin", "AF", "Africa", "BJ");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("BMU", "Bermuda", "NA", "North America", "BM");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("BTN", "Bhutan", "SS", "South Asia", "BT");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("BOL", "Bolivia (Plurinational State of)", "SA", "South America", "BO");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("BES", "Bonaire, Sint Eustatius and Saba", "SA", "South America", "");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("BIH", "Bosnia and Herzegovina", "EU", "Europe", "BA");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("BWA", "Botswana", "AF", "Africa", "BW");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("BRA", "Brazil", "SA", "South America", "BR");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("VGB", "British Virgin Islands", "SA", "South America", "VG");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("BRN", "Brunei Darussalam", "OC", "Oceania", "BN");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("BGR", "Bulgaria", "EU", "Europe", "BG");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("BFA", "Burkina Faso", "AF", "Africa", "BF");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("BDI", "Burundi", "AF", "Africa", "BI");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("CPV", "Cabo Verde", "AF", "Africa", "CV");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("KHM", "Cambodia", "SS", "South Asia", "KH");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("CMR", "Cameroon", "AF", "Africa", "CM");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("CAN", "Canada", "NA", "North America", "CA");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("CYM", "Cayman Islands", "SA", "South America", "KY");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("CAF", "Central African Republic", "AF", "Africa", "CF");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("TCD", "Chad", "AF", "Africa", "TD");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("CHL", "Chile", "SA", "South America", "CL");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("CHN", "China", "SS", "South Asia", "CN");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("HKG", "China, Hong Kong Special Administrative Region", "SS", "South Asia", "HK");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("MAC", "China, Macao Special Administrative Region", "SS", "South Asia", "MO");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("COL", "Colombia", "SA", "South America", "CO");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("COM", "Comoros", "AF", "Africa", "KM");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("COG", "Congo", "AF", "Africa", "CG");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("COK", "Cook Islands", "OC", "Oceania", "CK");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("CRI", "Costa Rica", "SA", "South America", "CR");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("CIV", "Côte d\'Ivoire", "AF", "Africa", "CI");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("HRV", "Croatia", "EU", "Europe", "HR");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("CUB", "Cuba", "SA", "South America", "CU");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("CUW", "Curaçao", "SA", "South America", "CW");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("CYP", "Cyprus", "EU", "Europe", "CY");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("CZE", "Czech Republic", "EU", "Europe", "CZ");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("PRK", "Democratic People\'s Republic of Korea", "SS", "South Asia", "KP");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("COD", "Democratic Republic of the Congo", "AF", "Africa", "CD");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("DNK", "Denmark", "EU", "Europe", "DK");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("DJI", "Djibouti", "AF", "Africa", "DJ");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("DMA", "Dominica", "SA", "South America", "DM");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("DOM", "Dominican Republic", "SA", "South America", "DO");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("ECU", "Ecuador", "SA", "South America", "EC");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("EGY", "Egypt", "AF", "Africa", "EG");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("SLV", "El Salvador", "SA", "South America", "SV");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("GNQ", "Equatorial Guinea", "AF", "Africa", "GQ");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("ERI", "Eritrea", "AF", "Africa", "ER");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("EST", "Estonia", "EU", "Europe", "EE");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("ETH", "Ethiopia", "AF", "Africa", "ET");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("FRO", "Faeroe Islands", "EU", "Europe", "FO");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("FLK", "Falkland Islands (Malvinas)", "SA", "South America", "FK");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("FJI", "Fiji", "OC", "Oceania", "FJ");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("FIN", "Finland", "EU", "Europe", "FI");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("FRA", "France", "EU", "Europe", "FR");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("GUF", "French Guiana", "SA", "South America", "GF");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("PYF", "French Polynesia", "OC", "Oceania", "PF");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("GAB", "Gabon", "AF", "Africa", "GA");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("GMB", "Gambia", "AF", "Africa", "GM");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("GEO", "Georgia", "EU", "Europe", "GE");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("DEU", "Germany", "EU", "Europe", "DE");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("GHA", "Ghana", "AF", "Africa", "GH");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("GIB", "Gibraltar", "EU", "Europe", "GI");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("GRC", "Greece", "EU", "Europe", "GR");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("GRL", "Greenland", "NA", "North America", "GL");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("GRD", "Grenada", "SA", "South America", "GD");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("GLP", "Guadeloupe", "SA", "South America", "GP");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("GUM", "Guam", "OC", "Oceania", "GU");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("GTM", "Guatemala", "SA", "South America", "GT");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("GGY", "Guernsey", "EU", "Europe", "GG");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("GIN", "Guinea", "AF", "Africa", "GN");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("GNB", "Guinea-Bissau", "AF", "Africa", "GW");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("GUY", "Guyana", "SA", "South America", "GY");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("HTI", "Haiti", "SA", "South America", "HT");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("VAT", "Holy See", "EU", "Europe", "VA");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("HND", "Honduras", "SA", "South America", "HN");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("HUN", "Hungary", "EU", "Europe", "HU");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("ISL", "Iceland", "EU", "Europe", "IS");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("IND", "India", "SS", "South Asia", "IN");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("IDN", "Indonesia", "OC", "Oceania", "ID");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("IRN", "Iran (Islamic Republic of)", "ME", "Middle East", "IR");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("IRQ", "Iraq", "ME", "Middle East", "IQ");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("IRL", "Ireland", "EU", "Europe", "IE");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("IMN", "Isle of Man", "EU", "Europe", "IM");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("ISR", "Israel", "ME", "Middle East", "IL");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("ITA", "Italy", "EU", "Europe", "IT");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("JAM", "Jamaica", "SA", "South America", "JM");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("JPN", "Japan", "SS", "South Asia", "JP");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("JEY", "Jersey", "EU", "Europe", "JE");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("JOR", "Jordan", "ME", "Middle East", "JO");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("KAZ", "Kazakhstan", "NS", "North Asia", "KZ");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("KEN", "Kenya", "AF", "Africa", "KE");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("KIR", "Kiribati", "OC", "Oceania", "KI");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("KWT", "Kuwait", "ME", "Middle East", "KW");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("KGZ", "Kyrgyzstan", "ME", "Middle East", "KG");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("LAO", "Lao People\'s Democratic Republic", "SS", "South Asia", "LA");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("LVA", "Latvia", "EU", "Europe", "LV");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("LBN", "Lebanon", "ME", "Middle East", "LB");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("LSO", "Lesotho", "AF", "Africa", "LS");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("LBR", "Liberia", "AF", "Africa", "LR");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("LBY", "Libya", "AF", "Africa", "LY");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("LIE", "Liechtenstein", "EU", "Europe", "LI");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("LTU", "Lithuania", "EU", "Europe", "LT");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("LUX", "Luxembourg", "EU", "Europe", "LU");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("MDG", "Madagascar", "AF", "Africa", "MG");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("MWI", "Malawi", "AF", "Africa", "MW");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("MYS", "Malaysia", "OC", "Oceania", "MY");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("MDV", "Maldives", "SS", "South Asia", "MV");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("MLI", "Mali", "AF", "Africa", "ML");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("MLT", "Malta", "EU", "Europe", "MT");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("MHL", "Marshall Islands", "OC", "Oceania", "MH");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("MTQ", "Martinique", "SA", "South America", "MQ");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("MRT", "Mauritania", "AF", "Africa", "MR");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("MUS", "Mauritius", "AF", "Africa", "MU");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("MYT", "Mayotte", "AF", "Africa", "YT");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("MEX", "Mexico", "NA", "North America", "MX");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("FSM", "Micronesia (Federated States of)", "OC", "Oceania", "FM");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("MCO", "Monaco", "EU", "Europe", "MC");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("MNG", "Mongolia", "NS", "North Asia", "MN");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("MNE", "Montenegro", "EU", "Europe", "ME");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("MSR", "Montserrat", "SA", "South America", "MS");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("MAR", "Morocco", "AF", "Africa", "MA");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("MOZ", "Mozambique", "AF", "Africa", "MZ");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("MMR", "Myanmar", "SS", "South Asia", "MM");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("NAM", "Namibia", "AF", "Africa", "NA");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("NRU", "Nauru", "OC", "Oceania", "NR");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("NPL", "Nepal", "SS", "South Asia", "NP");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("NLD", "Netherlands", "EU", "Europe", "NL");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("NCL", "New Caledonia", "OC", "Oceania", "NC");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("NZL", "New Zealand", "OC", "Oceania", "NZ");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("NIC", "Nicaragua", "SA", "South America", "NI");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("NER", "Niger", "AF", "Africa", "NE");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("NGA", "Nigeria", "AF", "Africa", "NG");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("NIU", "Niue", "OC", "Oceania", "NU");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("NFK", "Norfolk Island", "OC", "Oceania", "NF");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("MNP", "Northern Mariana Islands", "OC", "Oceania", "MP");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("NOR", "Norway", "EU", "Europe", "NO");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("OMN", "Oman", "ME", "Middle East", "OM");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("PAK", "Pakistan", "ME", "Middle East", "PK");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("PLW", "Palau", "OC", "Oceania", "PW");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("PSE", "Palestine", "ME", "Middle East", "PS");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("PAN", "Panama", "SA", "South America", "PA");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("PNG", "Papua New Guinea", "OC", "Oceania", "PG");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("PRY", "Paraguay", "SA", "South America", "PY");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("PER", "Peru", "SA", "South America", "PE");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("PHL", "Philippines", "SS", "South Asia", "PH");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("PCN", "Pitcairn", "OC", "Oceania", "PN");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("POL", "Poland", "EU", "Europe", "PL");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("PRT", "Portugal", "EU", "Europe", "PT");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("PRI", "Puerto Rico", "SA", "South America", "PR");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("QAT", "Qatar", "ME", "Middle East", "QA");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("KOR", "Republic of Korea", "SS", "South Asia", "KR");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("MDA", "Republic of Moldova", "EU", "Europe", "MD");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("REU", "Réunion", "AF", "Africa", "RE");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("ROU", "Romania", "EU", "Europe", "RO");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("RUS", "Russian Federation", "NS", "North Asia", "RU");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("RWA", "Rwanda", "AF", "Africa", "RW");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("BLM", "Saint Barthélemy", "SA", "South America", "BL");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("SHN", "Saint Helena", "AF", "Africa", "SH");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("KNA", "Saint Kitts and Nevis", "SA", "South America", "KN");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("LCA", "Saint Lucia", "SA", "South America", "LC");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("MAF", "Saint Martin (French part)", "SA", "South America", "MF");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("SPM", "Saint Pierre and Miquelon", "NA", "North America", "PM");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("VCT", "Saint Vincent and the Grenadines", "SA", "South America", "VC");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("WSM", "Samoa", "OC", "Oceania", "WS");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("SMR", "San Marino", "EU", "Europe", "SM");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("STP", "Sao Tome and Principe", "AF", "Africa", "ST");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("SAU", "Saudi Arabia", "ME", "Middle East", "SA");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("SEN", "Senegal", "AF", "Africa", "SN");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("SRB", "Serbia", "EU", "Europe", "RS");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("SYC", "Seychelles", "AF", "Africa", "SC");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("SLE", "Sierra Leone", "AF", "Africa", "SL");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("SGP", "Singapore", "SS", "South Asia", "SG");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("SXM", "Sint Maarten (Dutch part)", "SA", "South America", "SX");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("SVK", "Slovakia", "EU", "Europe", "SK");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("SVN", "Slovenia", "EU", "Europe", "SI");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("SLB", "Solomon Islands", "OC", "Oceania", "SB");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("SOM", "Somalia", "AF", "Africa", "SO");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("ZAF", "South Africa", "AF", "Africa", "ZA");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("SSD", "South Sudan", "AF", "Africa", "SS");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("ESP", "Spain", "EU", "Europe", "ES");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("LKA", "Sri Lanka", "SS", "South Asia", "LK");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("SDN", "Sudan", "AF", "Africa", "SD");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("SUR", "Suriname", "SA", "South America", "SR");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("SJM", "Svalbard and Jan Mayen Islands", "EU", "Europe", "SJ");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("SWZ", "Swaziland", "AF", "Africa", "SZ");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("SWE", "Sweden", "EU", "Europe", "SE");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("CHE", "Switzerland", "EU", "Europe", "CH");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("SYR", "Syrian Arab Republic", "ME", "Middle East", "SY");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("TWN", "Taiwan", "SS", "South Asia", "TW");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("TJK", "Tajikistan", "ME", "Middle East", "TJ");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("THA", "Thailand", "SS", "South Asia", "TH");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("MKD", "The former Yugoslav Republic of Macedonia", "EU", "Europe", "MK");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("TLS", "Timor-Leste", "OC", "Oceania", "TL");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("TGO", "Togo", "AF", "Africa", "TG");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("TKL", "Tokelau", "OC", "Oceania", "TK");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("TON", "Tonga", "OC", "Oceania", "TO");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("TTO", "Trinidad and Tobago", "SA", "South America", "TT");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("TUN", "Tunisia", "AF", "Africa", "TN");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("TUR", "Turkey", "EU", "Europe", "TR");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("TKM", "Turkmenistan", "ME", "Middle East", "TM");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("TCA", "Turks and Caicos Islands", "SA", "South America", "TC");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("TUV", "Tuvalu", "OC", "Oceania", "TV");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("UGA", "Uganda", "AF", "Africa", "UG");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("UKR", "Ukraine", "EU", "Europe", "UA");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("ARE", "United Arab Emirates", "ME", "Middle East", "AE");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("GBR", "United Kingdom of Great Britain and Northern Ireland", "EU", "Europe", "GB");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("TZA", "United Republic of Tanzania", "AF", "Africa", "TZ");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("USA", "United States of America", "NA", "North America", "US");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("VIR", "United States Virgin Islands", "SA", "South America", "VI");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("URY", "Uruguay", "SA", "South America", "UY");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("UZB", "Uzbekistan", "ME", "Middle East", "ZU");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("VUT", "Vanuatu", "OC", "Oceania", "VU");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("VEN", "Venezuela (Bolivarian Republic of)", "SA", "South America", "VE");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("VNM", "Viet Nam", "SS", "South Asia", "VN");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("WLF", "Wallis and Futuna Islands", "OC", "Oceania", "WF");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("ESH", "Western Sahara", "AF", "Africa", "EH");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("YEM", "Yemen", "ME", "Middle East", "YE");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("ZMB", "Zambia", "AF", "Africa", "ZM");
INSERT INTO {wp_projectmanager_countries} (code, name, region_code, region_name, code2) VALUES ("ZWE", "Zimbabwe", "AF", "Africa", "ZW");
